name: Data Science notes
description: big data, R and more
repo: https://github.com/dselivanov/dselivanov.github.io

url: http://dsnotes.com
permalink: "articles/:title"

exclude:
  - COPYING
  - README.md
  - Makefile
  - src
  - figure
  - _drafts

highlighter: rouge

markdown: kramdown

comments: true

gems:
  - jekyll-redirect-from